language: php

php:
  - 5.6
  - hhvm
 
env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*

